#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 26 14:11:37 2020
@author: dowlettealameldin
"""


import numpy as np
import math
import pandas as pd 
#
#
data='/Users/dowlettealameldin/exp/Test7/Test7PART2DLC_resnet50_Trial3Mar23shuffle1_10000.csv'
#
#t=data[:,0]
df = pd.read_csv(data,header=1) 
df1 = df[['centroid','centroid.1']]

x=df.iloc[:,7]
y=df.iloc[:,8]

w=x[:-1].to_numpy()
z=y[:-1].to_numpy()
a=x[1:].to_numpy()
b=y[1:].to_numpy()

dx = w-a
dy = z-b


distanceWalked = ((dx **2 + dy **2)**.5)


totaldistance= sum(distanceWalked)
